UR-SS/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('account/', include('account.urls')),
     path('summernote/', include('django_summernote.urls')),
     path('editor/', include('django_summernote.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

UR-SS/core/urls.py
from django.urls import path
from core.views import *

urlpatterns = [
    path('', LandingPageView.as_view(), name = 'landing'),
    path('register', clientRegister, name = 'client-register'),
    path('login', clientLogin, name = 'client-login'),
    path('logout', logoutuser, name = 'client-logout'),
    path('categories/', CategoriesView.as_view(), name = 'categories'),
    path('posts/', ClientPostView.as_view(), name = 'client-posts'),
    path('category-posts/<str:cats>/', CategoryPostView, name = 'category-posts'),
    path('post-detail/<slug:slug>', PostDetailView.as_view(), name = 'client-post-detail'),
    path('feedback', FeedbackView.as_view(), name = 'client-feedback'),
    path('confirm-payment/<int:pk>', confirm_payment, name='add'),
    path('confirm-category-payment/<int:pk>', confirm_payment_category, name = "add_category"),
    
    # Author urls  
    path('home/', HomePageView.as_view(), name = 'home'),
    path('terms-conditions/', TermsView.as_view(), name = 'terms'),
    path('new-post', NewPostView.as_view(), name = 'new-post'),
    path('post-list', PostListView.as_view(), name ='post-list'),
    path('paid-posts', PaidPostListView.as_view(), name ='paid-post'),
    path('unpaid-post', UnpaidPostListView.as_view(), name ='unpaid-post'),
    path('profile', ProfileView.as_view(), name ='profile'),    
                                         
]

UR-SS/core/models.py
from django.db import models
from account.models import CustomUser
from django.urls import reverse

payments = (
    ('Paid','Paid'),
    ('Unpaid','Unpaid')
)

# post category
class Category(models.Model):
    name = models.CharField(max_length=255, default="za") 
    def __str__(self):
        return self.name


# posts
class Post(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length = 225)
    intro =models.CharField(max_length=225, null=True)
    body = models.TextField()
    category = models.CharField(max_length=225, default="Music") 
    slug = models.SlugField(null=True)
    price= models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = "images")
    status = models.CharField(max_length=100, choices=payments, blank=True, default='Unpaid')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
            ordering = ['created'] 

    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
      return reverse('client-post-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.title)
        super().save(*args, **kwargs)
    

class Testimonial(models.Model):
     First_name = models.CharField(max_length=250,null=True)
     Last_name = models.CharField(max_length=250,null=True)
     Email_name = models.CharField(max_length=250,null=True)
     Image = models.ImageField(upload_to = "images",null=True)
     Message = models.TextField()

     def __str__(self):
          return self.First_name + " " + self.Last_name + " " + self.Message
    
     def full_name(self):
        return self.First_name + " " + self.Last_name

UR-SS/templates/client/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>UR-SS - Unemployment Reduction Support System</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
   <div class="container">
     <a class="navbar-brand" href="{% url 'landing' %}"><span>UR</span>SS</a>

     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
       <span class="oi oi-menu"></span> Menu
   </button>

   <div class="collapse navbar-collapse" id="ftco-nav">
       <ul class="navbar-nav ml-auto">
         <li class="nav-item {% block home-state %}{% endblock %}"><a href="{% url 'landing' %}" class="nav-link">Home</a></li>
         <li class="nav-item {% block category-state %}{% endblock %}"><a href="{% url 'categories' %}" class="nav-link">Category</a></li>
        

         {% if user.id and user.is_client %}
         <li class="nav-item {% block post-state %}{% endblock %}"><a href="{% url 'client-posts' %}" class="nav-link">Posts</a></li>
         <li class="nav-item "><a href="#" class="nav-link text-white">user: <b>{{user.first_name}}</b></a></li>
         <li class="nav-item "><a href="{% url 'client-logout' %}" class="nav-link text-danger">logout</a></li>
         
         {% else %}
         <li class="nav-item {% block feedback-state %}{% endblock %}"><a href="{% url 'client-feedback' %}" class="nav-link">Feedback</a></li>
         <li class="nav-item "><a href="{% url 'client-login' %}" class="nav-link">Posts</a></li>
         {%endif%}
         
     </ul>
 </div>
</div>
</nav>


<!-- END nav -->

{% block content %}

{% endblock %}


<!-- Footer starts here -->
<footer class="ftco-footer ftco-no-pt">
  <div class="container">
    <div class="row mb-5">
  
</div>
<div class="row">
  <div class="col-md-12 text-center">

    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved <i class="fa fa-heart" aria-hidden="true"></i> by UR-SS 
      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
  </div>
</div>
</div>
</footer>
<!-- Footer ends here -->


<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
  

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


</script>

</body>
</html>

UR-SS/templates/client/category-posts.html
{% extends 'client/base.html' %}
{% load static %}
{% block post-state %}active{% endblock %}
{% block content %}

	
	<section class="ftco-section bg-light">
		<div class="container">
			<div class="row">
				
				<div class="col-lg-12">
					<div class="sidebar-box bg-white ftco-animate">
						<form action="#" class="search-form">
							<div class="form-group">
								<span class="icon fa fa-search"></span>
								<input type="text" class="form-control" placeholder="Search...">
							</div>
						</form>
					</div>
					<div class="row">




						{%for posts in category_post_list%}
            
						<div class="col-md-4 d-flex align-items-stretch ftco-animate">
							<div class="project-wrap">
								<a href="{{posts.get_absolute_url}}" class="img" style="background-image: url('{{posts.image.url}}');">
	
									<span class="price">{{posts.title}}</span>
								</a>
								<div class="text p-4">
									<p><a href="#" style="color:black; font-family: 'Times New Roman', Times, serif;">{{posts.intro}}</a></p>
									<p class="advisor">Author <span>{{posts.author.full_name}}</span></p>
									<ul class="d-flex justify-content-between">
										<li><span class="flaticon-shower"></span>Amount</li>
										<li class="price">{{posts.price}}RWF</li>
									</ul>
									{%if posts.status == 'Paid'%}
									<ul class="d-flex justify-content-between">
										<li><span class="flaticon-shower"></span></li>
										<li class="price">
											<a href="{{posts.get_absolute_url}}"><button type="button" class="btn btn-primary text-light" >view</button></a></li>
									</ul>
									{% else %}
									
									<ul class="d-flex justify-content-between">
										<li><span class="flaticon-shower"></span></li>
										<li class="price">
											<button type="button" class="btn btn-primary" onclick="makePayment()">Pay Now</button></li>
									</ul>

									{% endif %}
								</div>
							</div>
						</div>
						{% endfor %}
					
					</div>
					<div class="row mt-5">
						<div class="col text-center">
							<div class="block-27">
								<ul>
									<li><a href="#">&lt;</a></li>
									<li class="active"><span>1</span></li>
									<li><a href="#">2</a></li>
									<li><a href="#">3</a></li>
									<li><a href="#">4</a></li>
									<li><a href="#">5</a></li>
									<li><a href="#">&gt;</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		

			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>		
			<script src="https://checkout.flutterwave.com/v3.js"></script>
			
			{%for post in category_post_list%}
			<script>
			
				function makePayment() {
				
					// let all_post = '{{all_post}}'.find(post=>post.id === post_id)
					
			
					FlutterwaveCheckout({
					  public_key: "FLWPUBK_TEST-ce742fc54e7e75b5dbb4c59b8f2d42e0-X",
					  tx_ref: "titanic-48981487343MDI0NzMx",
					  amount: '{{post.price}}',
					  currency: "RWF",
					  payment_options: "card, mobilemoneyghana, ussd",
					  redirect_url: "http://127.0.0.1:8000/confirm-payment/" + '{{post.id}}',
					  meta: {
						consumer_id: 23,
						consumer_mac: "92a3-912ba-1192a",
					  },
					  customer: {
						email: "zacheekobura20@gmail.com",
						phone_number: "08102909304",
						name: "Rose DeWitt Bukater",
					  },
					  customizations: {
						title: "URSS",
						description: "Payment for an awesome post",
						logo: "https://www.logolynx.com/images/logolynx/22/2239ca38f5505fbfce7e55bbc0604386.jpeg",
					  },
					});
				  }
			
			
			</script>
			{%endfor%}
			</section>
			
			
			<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
				<div class="modal-dialog">
				  <div class="modal-content">
					<div class="modal-header">
					  <h1 class="modal-title fs-5" id="staticBackdropLabel">Please pay for this post to read more!</h1>
					  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						How to pay? 
						<br>
						Just click on <b>pay now</b> button and you'll be redirected to the payment page where you'll be asked to fill out your Master or Credit card 
						
						, after making payment you will be able to read more. Thank you!
			
					</div>
					<div class="modal-footer">
					  <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
					 <button type="button" class="btn btn-primary" onclick="makePayment()">Pay Now</button>
					</div>
				  </div>
				</div>
			  </div>
			
			{% endblock %}

UR-SS/templates/client/category.html
{% extends 'client/base.html' %}
{% load static %}
{% block category-state %}active{% endblock %}
{% block content %}
<section class="ftco-section bg-dark">
<div class="container text-center" >
    <h1 class="text-light">home > Categories</h1>
</div>
</section> 
<section class="ftco-section bg-dark">
		<div class="container">
 
				
<div class="row justify-content-center">
    {%if category_list%}
    {% if user.id and user.is_client %}
    {%for category in category_list%}  
    <div class="col-md-3 col-lg-3">
        <a  href="{% url 'category-posts' category %}" class="course-category img d-flex align-items-center bg-dark justify-content-center">
              <div class="text w-200 text-center">
                 <h3>{{category.name}}</h3>
               
             </div>
            </a>
     </div>
     {%endfor%}
     {% else %}
     {%for category in category_list%} 
     <div class="col-md-3 col-lg-3">
        <a  href="{% url 'client-login' %}" class="course-category img d-flex align-items-center bg-dark justify-content-center">
              <div class="text w-200 text-center">
                 <h3>{{category.name}}</h3>
               
             </div>
            </a>
     </div>

     {%endfor%}
     {%endif%}
     {%endif%}

</div>
</section>

{% endblock %}

UR-SS/templates/client/client-post-detail.html
{% extends 'client/base.html' %}
{% load static %}
{% block post-state %}active{% endblock %}
{% block content %}


	<section class="ftco-section bg-light">
		<div class="container">
			<div class="row">
				
				<div class="col-lg-12">
					<div class="sidebar-box bg-white ftco-animate text-center text-bold">
						<h>{{object.title}}</h>
					</div>
					<div class="row text-dark">
                        {{ object.body|safe }}
					
					</div>
				
				</div>
			</div>
		</section>
{%endblock%}

UR-SS/templates/client/contact.html
{% extends 'client/base.html' %}
{% load static %}

{% block content %}


	<section class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_2.jpg');">
		<div class="overlay"></div>
		<div class="container">
			<div class="row no-gutters slider-text align-items-end justify-content-center">
				<div class="col-md-9 ftco-animate pb-5 text-center">
					<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>Contact us <i class="fa fa-chevron-right"></i></span></p>
					<h1 class="mb-0 bread">Contact us</h1>
				</div>
			</div>
		</div>
	</section>

	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-12">
					<div class="wrapper">
						<div class="row no-gutters">
							<div class="col-lg-8 col-md-7 order-md-last d-flex align-items-stretch">
								<div class="contact-wrap w-100 p-md-5 p-4">
									<h3 class="mb-4">Get in touch</h3>
									<form method="POST" id="contactForm" name="contactForm" class="contactForm">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label class="label" for="name">Full Name</label>
													<input type="text" class="form-control" name="name" id="name" placeholder="Name">
												</div>
											</div>
											<div class="col-md-6"> 
												<div class="form-group">
													<label class="label" for="email">Email Address</label>
													<input type="email" class="form-control" name="email" id="email" placeholder="Email">
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<label class="label" for="subject">Subject</label>
													<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject">
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<label class="label" for="#">Message</label>
													<textarea name="message" class="form-control" id="message" cols="30" rows="4" placeholder="Message"></textarea>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<input type="submit" value="Send Message" class="btn btn-primary">
													<div class="submitting"></div>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="col-lg-4 col-md-5 d-flex align-items-stretch">
								<div class="info-wrap bg-primary w-100 p-md-5 p-4">
									<h3>Let's get in touch</h3>
									<p class="mb-4">We're open for any suggestion or just to have a chat</p>
									<div class="dbox w-100 d-flex align-items-start">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-map-marker"></span>
										</div>
										<div class="text pl-3">
											<p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
										</div>
									</div>
									<div class="dbox w-100 d-flex align-items-center">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-phone"></span>
										</div>
										<div class="text pl-3">
											<p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
										</div>
									</div>
									<div class="dbox w-100 d-flex align-items-center">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-paper-plane"></span>
										</div>
										<div class="text pl-3">
											<p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
										</div>
									</div>
									<div class="dbox w-100 d-flex align-items-center">
										<div class="icon d-flex align-items-center justify-content-center">
											<span class="fa fa-globe"></span>
										</div>
										<div class="text pl-3">
											<p><span>Website</span> <a href="#">yoursite.com</a></p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-12 mt-5">
					<div id="map" class="bg-white"></div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

UR-SS/templates/client/index.html
{% extends 'client/base.html' %}
{% load static %}
{% block home-state %}active{% endblock %}
{% block content %}

{% if user.id and user.is_client %}
<div class="hero-wrap js-fullheight" style="background-color:black;"></div>
{% else %}
<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/back_2.jpeg' %}');">
{%endif%}
<div class="hero-wrap js-fullheight" >
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center" data-scrollax-parent="true">
      <div class="col-md-7 ftco-animate">
        {% if  user.id and user.is_client %}
        <p></p>
        {% else %}
        <h1 class="mb-4">We Are Online Platform For selling business ideas</h1>
        <p class="caps">  </p>
        <p class="mb-0"><a href="{% url 'client-login' %}" class="btn btn-primary">Login</a> <a href="{% url 'client-register' %}" class="btn btn-white">Register</a></p>
        {% endif %}
    </div>
</div>
</div>
</div>




<section class="ftco-section">
   <div class="container">
      <div class="row justify-content-center pb-4">
          <div class="col-md-12 heading-section text-center ftco-animate">
          	<span class="subheading">Start Earning Today</span>
            <h2 class="mb-4">Browse Posts by Category</h2>
        </div>
    </div>
   
        <div class="row justify-content-center">
        {%if category_list%}
        {% if user.id and user.is_client %}
        {%for category in category_list%}  
        <div class="col-md-3 col-lg-3">
            <a  href="{% url 'category-posts' category %}" class="course-category img d-flex align-items-center bg-dark justify-content-center">
                  <div class="text w-200 text-center">
                     <h3>{{category.name}}</h3>
                   
                 </div>
                </a>
         </div>
         {%endfor%}
         {% else %}
         {%for category in category_list%} 
         <div class="col-md-3 col-lg-3">
            <a  href="{% url 'client-login' %}" class="course-category img d-flex align-items-center bg-dark justify-content-center">
                  <div class="text w-200 text-center">
                     <h3>{{category.name}}</h3>
                   
                 </div>
                </a>
         </div>

         {%endfor%}
         {%endif%}
         {%endif%}
        

</div>
</div>
</section>



<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url({% static 'images/back_4.webp' %});">
 <div class="overlay"></div>
 <div class="container">
    <div class="row">
       <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
         <div class="block-18 d-flex align-items-center">
            <div class="icon"><span class="flaticon-online"></span></div>
            <div class="text">
             <strong class="number" data-number="400">0</strong>
             <span>Clients</span>
         </div>
     </div>
 </div>
 <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
     <div class="block-18 d-flex align-items-center">
        <div class="icon"><span class="flaticon-graduated"></span></div>
        <div class="text">
         <strong class="number" data-number="4500">0</strong>
         <span>Authors</span>
     </div>
 </div>
</div>
<div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
 <div class="block-18 d-flex align-items-center">
    <div class="icon"><span class="flaticon-instructor"></span></div>
    <div class="text">

     <span class="">
        {{post_list_num}}
     </span>
 
     <span>Posts</span>
 </div>
</div>
</div>
<div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
 <div class="block-18 d-flex align-items-center">
    <div class="icon"><span class="flaticon-tools"></span></div>
    <div class="text">
     <strong class="number" data-number="30">0</strong>
     <span>Testimonials</span>
 </div>
</div>
</div>
</div>
</div>
</section>

<section class="ftco-section ftco-about img">
   <div class="container">
      <div class="row d-flex">
         <div class="col-md-12 about-intro">
            <div class="row">
               <div class="col-md-6 d-flex">
                  <div class="d-flex about-wrap">
                     <div class="img d-flex align-items-center justify-content-center" style="background-image:url({% static 'images/back_7.jpg' %});">
                     </div>
                     <div class="img-2 d-flex align-items-center justify-content-center" style="background-image:url({% static 'images/back_8.jpg' %});">
                     </div>
                    </div>
                </div>
             <div class="col-md-6 pl-md-5 py-5">
                 <div class="row justify-content-start pb-3">
                     <div class="col-md-12 heading-section ftco-animate">
                         <span class="subheading">Be more Productive</span>
                         <h2 class="mb-4">Know more about us!</h2>
                     <p>The reason as to why this system was developed, was to provide for young graduates platform that can help them to sell their business ideas for them to raise money and create their own jobs rather than remaining unemployment. 
                        Our system will provide a platform that will feature different business ideas that can be successfully implemented with full detailed information convincing and profitable for those who will be interested to buy them.</p>
                     <p><a href="{% url 'client-feedback' %}" class="btn btn-primary">Get in touch with us</a></p>
                    </div>
             </div>
            </div>
     </div>
 </div>
</div>
</div>
</section>

<section class="ftco-intro ftco-section">
 <div class="container">
    <div class="row justify-content-center">
       <div class="col-md-12 text-center">
          <div class="img"  style="background-image: url({% static 'images/back_5.webp' %});">
             <div class="overlay"></div>
             <h2>We Are URSS - Unemployment Reduction Support System</h2>
             <p>Join the group of authors and contribute to the society</p>
             <p class="mb-0"><a href="{% url 'register' %}" class="btn btn-primary px-4 py-3">Sign Up</a></p>
         </div>
     </div>
 </div>
</div>
</section>

<section class="ftco-section testimony-section bg-light">
    <div class="overlay" style="background-image: url({% static 'images/zachee.jpeg' %});"></div>
   <div class="container">
    <div class="row pb-4">
      <div class="col-md-7 heading-section ftco-animate">
         <span class="subheading">Testimonial</span>
         <h2 class="mb-4">What Our Clients Say</h2>
     </div>
 </div>
</div>
<div class="container">
    <div class="row ftco-animate">
        {%if testimonial_list%}
     {%for  testimony in testimonial_list%}
        <div class="col-md-4">
            <br><br>
                <div class="item">
                    <div class="testimony-wrap">
                        <div class="text">
                            <p class="star">
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                            </p>
                        </div>
                        <p class="mb-4">{{testimony.Message}}</p>
                        <div class="d-flex align-items-center">
                                <div class="user-img" style="background-image: url('{{testimony.Image.url}}')"></div>
                            <div class="pl-3">
                                <p class="name">{{testimony.full_name}}</p>
                                <span class="position"></span>
                            </div>
                        </div>
                    </div>
              </div>
        
        </div>
    
        {%endfor%}
        {%endif%}
    </div>

</div>




</section>
{% endblock %}